id: I83C0C787
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T13:54:00+00:00'
last_modified: '2022-06-08T08:25:35.854226+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12338
  title: ནི་གུ་མའི་སྙན་བརྒྱུད་ཀྱི་གནད་ཡིག་སྙིང་པོ་ཀུན་འདུས་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EA49:
      image_group_id: I1KG12395
      title: ''
      total_pages: 130
      order: 1
      base_file: EA49.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
